[package]
name = "terraform"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.18"
rsa = "0.10.0-rc.18"
rcgen = "0.14.8"
server = { path = "../server" }
const_format = "0.2.36"
rand = "0.10.1"
toml = "1.1.2"
clap = { version = "4.6.1", features = ["derive"] }

# for testing
[dev-dependencies]
tempfile = "3.8"
