[package]
name = "shared_library"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.1"
thiserror = "2.0.18"
wincode = { version = "0.5.4", features = ["derive"] }
sha2 = { version = "0.10", features = ["oid"] }
rsa = { version = "0.9.10", features = ["pem", "sha2"] }
const_format = "0.2.36"
hex = "0.4.3"
