[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
rustls = { version = "0.23.40", features = ["ring"] }
tokio = { version = "1.52.3", features = ["rt-multi-thread", "net", "io-util", "macros"] }
tokio-rustls = "0.26.4"
rustls-pemfile = "2.2.0"
serde = { version = "1", features = ["derive"] }
toml = "1.1.2"
thiserror = "2.0.18"
rsa = { version = "0.9.10", features = ["pem"] }
tokio-util = { version = "0.7.18", features = ["codec"] }
futures = "0.3.32"
shared_library = { path = "../shared_library" }
rkyv = "0.8.16"
tracing-appender = "0.2.5"
rustls-pki-types = "1.14.1"
