[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
rustls = { version = "0.23.40", default-features = false, features = ["ring", "std", "tls12"] }
tokio-rustls = { version = "0.26.4", default-features = false, features = ["ring"] }
tokio = { version = "1.52.3", features = ["rt-multi-thread", "net", "io-util", "time", "macros", "signal"] }
rustls-pemfile = "2.2.0"
serde = { version = "1", features = ["derive"] }
toml = "1.1.2"
thiserror = "2.0.18"
rsa = { version = "0.9.10", features = ["pem", "sha2"] }
tokio-util = { version = "0.7.18", features = ["codec", "rt"] }
futures = "0.3.32"
shared_library = { path = "../shared_library" }
rustls-pki-types = "1.14.1"
sqlx = { version = "0.9.0-alpha.1", features = ["runtime-tokio", "sqlite", "macros"] }
tracing = { version = "0.1", features = ["max_level_debug", "release_max_level_info"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2.5"
argon2 = { version = "0.5.3", features = ["password-hash", "std", "rand"] }
wincode = "0.5.4"
dashmap = "6.2.1"
tempfile = "3.27.0"
sha2 = { version = "0.11.0", features = ["oid"] }
hex = "0.4.3"
sntpc = { version = "0.10.1", features = ["std"] }
sntpc-net-tokio = "1"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0.102"
rand = "0.8.6"

# for testing
[dev-dependencies]
tempfile = "3.8"

[lints.clippy]
arithmetic_side_effects = "deny"
